# Generated by Django 3.2.9 on 2022-01-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0002_auto_20220103_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='avancement',
            old_name='id_affaire',
            new_name='id_affaires',
        ),
        migrations.RenameField(
            model_name='avancement',
            old_name='id_piece',
            new_name='id_pieces',
        ),
        migrations.AddField(
            model_name='chargementcamions',
            name='id_camions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.camions'),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='id_outils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.outils'),
        ),
        migrations.AlterField(
            model_name='chargementcamions',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='id_affaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.CreateModel(
            name='MontageMecanoSoude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
            ],
        ),
    ]
