# Generated by Django 3.2.9 on 2022-01-20 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_auto_20220105_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='pieces',
            old_name='id_affaire',
            new_name='id_affaires',
        ),
        migrations.AddField(
            model_name='affaires',
            name='budget_heures',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affaires',
            name='budget_hydraulique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affaires',
            name='budget_matiere',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affaires',
            name='budget_mecanique',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affaires',
            name='budget_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='affaires',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='avancement',
            name='Peinture',
            field=models.CharField(max_length=63,default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='ajustage_montage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='avancement',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='debit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='montage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='soudure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avancement',
            name='zone_colisage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandes',
            name='date_commande',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='date_reception',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='devis',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='commandes',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='budget_fab',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='colisage',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='compagnon',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='couleur_peinture',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='etat_ajustage',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='etat_debits',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='etat_decoupe_cn',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='etat_percage',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='etat_soudure',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='feuilles_de_debit',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='livraison',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='miniature',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='montage_mecano_soude',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='nb_anomalies',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='nesting',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='plans',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='poids',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='reference',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='taux_de_complexite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='factures',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suivi.affaires'),
        ),
        migrations.AddField(
            model_name='outils',
            name='date_livraison',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='date_offre',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='lien_offre',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='numero_affaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
