# Generated by Django 3.2.9 on 2022-01-20 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0004_auto_20220120_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='camions',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
    ]
