# Generated by Django 3.2.9 on 2022-01-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0006_budget_id_affaires'),
    ]

    operations = [
        migrations.AddField(
            model_name='outils',
            name='nom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
