# Generated by Django 3.2.9 on 2022-01-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0007_outils_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outils',
            name='numero_affaire',
        ),
    ]
