# Generated by Django 3.2.9 on 2022-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0009_auto_20220121_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancement',
            name='Peinture',
            field=models.BooleanField(default=False),
        ),
    ]
