# Generated by Django 4.0.2 on 2022-02-23 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0010_alter_avancement_peinture'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancement',
            name='id_nomenclature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.nomenclature'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='id_outils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.outils'),
        ),
        migrations.AlterField(
            model_name='camions',
            name='transporteur',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
