# Generated by Django 4.0.2 on 2022-02-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0011_avancement_id_nomenclature_nomenclature_id_outils_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandes',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='suivi.affaires'),
        ),
    ]
