# Generated by Django 4.0.2 on 2022-02-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0012_commandes_id_affaires'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('nom', models.CharField(max_length=63, null=True)),
                ('id_affaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
                ('id_ensemble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.ensembles')),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces')),
            ],
        ),
    ]
