# Generated by Django 4.0.2 on 2022-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0013_pieceensemble'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceensemble',
            name='type',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
