# Generated by Django 4.0.2 on 2022-02-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0014_pieceensemble_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieces',
            name='of',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
