# Generated by Django 4.0.2 on 2022-03-09 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0015_alter_pieces_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvancementEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.CharField(max_length=16, null=True)),
                ('montage', models.CharField(max_length=16, null=True)),
                ('soudure', models.CharField(max_length=16, null=True)),
                ('ajustage_montage', models.CharField(max_length=16, null=True)),
                ('peinture', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvancementSousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sousensemble', models.IntegerField(null=True)),
                ('debit', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
                ('montage', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
                ('soudure', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
                ('ajustage_montage', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
                ('avancement', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
                ('peinture', models.CharField(choices=[('NC', 'Non commencé'), ('EC', 'En cours'), ('TR', 'Terminé')], default='NC', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=127)),
                ('numero', models.IntegerField(null=True)),
                ('poids', models.IntegerField(null=True)),
                ('plans', models.CharField(max_length=127, null=True)),
                ('compagnon', models.CharField(max_length=127, null=True)),
                ('nesting', models.CharField(max_length=127, null=True)),
                ('feuilles_de_debit', models.CharField(max_length=127, null=True)),
                ('etat_decoupe_cn', models.CharField(max_length=127, null=True)),
                ('etat_debits', models.CharField(max_length=127, null=True)),
                ('etat_percage', models.CharField(max_length=127, null=True)),
                ('montage_mecano_soude', models.CharField(max_length=127, null=True)),
                ('etat_soudure', models.CharField(max_length=127, null=True)),
                ('etat_ajustage', models.CharField(max_length=127, null=True)),
                ('couleur_peinture', models.CharField(max_length=127, null=True)),
                ('colisage', models.CharField(max_length=127, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='affaires',
            name='numero',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='photos',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='devis',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='commandes',
            name='id_affaires',
        ),
        migrations.AddField(
            model_name='commandes',
            name='id_affaires',
            field=models.ManyToManyField(to='suivi.Affaires'),
        ),
        migrations.AlterField(
            model_name='factures',
            name='facture',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.RemoveField(
            model_name='factures',
            name='id_affaires',
        ),
        migrations.AddField(
            model_name='factures',
            name='id_affaires',
            field=models.ManyToManyField(to='suivi.Affaires'),
        ),
        migrations.AlterField(
            model_name='montagemecanosoude',
            name='date_debut',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='montagemecanosoude',
            name='date_fin',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='outils',
            name='date_livraison',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='outils',
            name='date_offre',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='outils',
            name='lien_offre',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.DeleteModel(
            name='Avancement',
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='id_ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.ensembles'),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='id_outils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.outils'),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='id_affaires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='id_sousensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.sousensemble'),
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='id_affaires',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='id_ensembles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.ensembles'),
        ),
        migrations.AddField(
            model_name='pieceensemble',
            name='id_sousensemble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.sousensemble'),
        ),
        migrations.AddField(
            model_name='pieces',
            name='id_sous_ensemble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.sousensemble'),
        ),
    ]
