# Generated by Django 4.0.2 on 2022-03-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0016_avancementensemble_avancementsousensemble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affaires',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
