# Generated by Django 4.0.2 on 2022-03-11 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0017_alter_affaires_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avancementsousensemble',
            name='avancement',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='compagnon',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='etat_ajustage',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='etat_debits',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='etat_decoupe_cn',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='etat_percage',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='etat_soudure',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='feuilles_de_debit',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='montage_mecano_soude',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='nesting',
        ),
        migrations.RemoveField(
            model_name='ensembles',
            name='plans',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='etat_ajustage',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='etat_debits',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='etat_decoupe_cn',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='etat_percage',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='etat_soudure',
        ),
        migrations.RemoveField(
            model_name='sousensemble',
            name='montage_mecano_soude',
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='avancement_global',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='decoupe_cn',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='commandes',
            name='paired_commandes',
            field=models.ManyToManyField(to='suivi.Commandes'),
        ),
        migrations.AddField(
            model_name='factures',
            name='paired_factures',
            field=models.ManyToManyField(to='suivi.Factures'),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='cout_unitaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='heures_fabrication',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='indice_de_complexite',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='of',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='revision',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='ajustage_montage',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='debit',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='montage',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='peinture',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='soudure',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.RemoveField(
            model_name='commandes',
            name='id_affaires',
        ),
        migrations.AddField(
            model_name='commandes',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
        migrations.RemoveField(
            model_name='factures',
            name='id_affaires',
        ),
        migrations.AddField(
            model_name='factures',
            name='id_affaires',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires'),
        ),
    ]
