# Generated by Django 4.0.2 on 2022-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0018_remove_avancementsousensemble_avancement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sousensemble',
            old_name='plans',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='pieces',
            name='plan',
            field=models.CharField(max_length=63, null=True),
        ),
    ]
