# Generated by Django 4.0.2 on 2022-03-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0019_rename_plans_sousensemble_plan_pieces_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementsousensemble',
            name='id_ensemble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.ensembles'),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='poids_unitaire',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='quantite',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sousensemble',
            name='poids',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sousensemble',
            name='quantite',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
