# Generated by Django 4.0.2 on 2022-03-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0020_avancementsousensemble_id_ensemble_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomenclature',
            name='numero_affaire',
        ),
    ]
