# Generated by Django 4.0.2 on 2022-03-16 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0021_remove_nomenclature_numero_affaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camions',
            name='capacite',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.datetime(2022, 3, 16, 10, 32, 49, 144267), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.datetime(2022, 3, 16, 10, 32, 49, 144267), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='poids',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chargementcamions',
            name='poids_total',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='chargementcamions',
            name='quantite_piece',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.datetime(2022, 3, 16, 10, 32, 49, 145268), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.datetime(2022, 3, 16, 10, 32, 49, 145268), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='sousensemble',
            name='cout_unitaire',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
