# Generated by Django 4.0.2 on 2023-03-31 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0024_chargementcamions_id_sous_ensemble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_heures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_hydraulique',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_matiere',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_mecanique',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.date(2023, 3, 31), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.date(2023, 3, 31), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.date(2023, 3, 31), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.date(2023, 3, 31), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='sousensemble',
            name='heures_fabrication',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sousensemble',
            name='revision',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, null=True)),
                ('telephone', models.CharField(max_length=63, null=True)),
                ('email', models.CharField(max_length=63, null=True)),
                ('id_affaires', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
            ],
        ),
    ]
