# Generated by Django 4.0.2 on 2023-04-28 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0025_budget_budget_total_alter_budget_budget_heures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=63)),
                ('prenom', models.CharField(max_length=63)),
                ('temps_hebdo', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='budget_heures',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='budget_hydraulique',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='budget_matiere',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='budget_mecanique',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='budget_total',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='fabrication',
        ),
        migrations.RemoveField(
            model_name='outils',
            name='date_offre',
        ),
        migrations.RemoveField(
            model_name='outils',
            name='options',
        ),
        migrations.RemoveField(
            model_name='outils',
            name='version_offre',
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ensembles',
            name='sym',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='budget_heures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='budget_hydraulique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='budget_matiere',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='budget_mecanique',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='budget_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outils',
            name='fabrication',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='outils',
            name='sym',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pieces',
            name='heures_soudure',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pieces',
            name='sym',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='heures_soudure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='sym',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.date(2023, 4, 28), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.date(2023, 4, 28), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.date(2023, 4, 28), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.date(2023, 4, 28), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='pieceensemble',
            name='type',
            field=models.CharField(choices=[('piece', 'piece'), ('sous-ensemble', 'sous-ensemble'), ('ensemble', 'ensemble')], default='piece', max_length=63),
        ),
        migrations.AlterField(
            model_name='pieces',
            name='quantite',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_estime', models.IntegerField(default=0, max_length=15)),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('etat', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=63)),
                ('type', models.CharField(max_length=63)),
                ('qualification', models.CharField(max_length=63)),
                ('unite', models.CharField(choices=[('K', 'kg'), ('Q', 'Qte')], max_length=15)),
                ('quantite', models.IntegerField(max_length=31, null=True)),
                ('id_affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
                ('id_compagnon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.compagnon')),
                ('id_ensemble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.ensembles')),
                ('id_piece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces')),
                ('id_sous_ensemble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.sousensemble')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.IntegerField(choices=[(1, 'Peintre'), (2, 'Débiteur'), (3, 'Soudeur'), (4, 'Trappeur'), (5, 'Chaudronnier'), (6, 'Monteur')], default=0, max_length=4)),
                ('categorie', models.CharField(choices=[('NON', 'Non'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='NON', max_length=63)),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.compagnon')),
            ],
        ),
        migrations.CreateModel(
            name='DebitScie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_profile', models.CharField(max_length=63, null=True)),
                ('etat', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=63)),
                ('id_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces')),
            ],
        ),
        migrations.CreateModel(
            name='DebitLaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epaisseur', models.CharField(choices=[('Non', 'Non'), ('Larmée', 'Larmée'), ('4', '4'), ('5', '5'), ('6', '6'), ('8', '8'), ('12', '12'), ('15', '15'), ('20', '20')], default='Non', max_length=8)),
                ('grade', models.CharField(max_length=16, null=True)),
                ('etat', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=63)),
                ('id_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces')),
            ],
        ),
        migrations.CreateModel(
            name='AvancementPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4)),
                ('montage', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4)),
                ('soudure', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4)),
                ('ajustage_montage', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4)),
                ('peinture', models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4)),
                ('type_tache', models.CharField(max_length=64)),
                ('complexite', models.CharField(choices=[('Facile', 'Facile'), ('Moyen', 'Moyen'), ('Difficile', 'Difficile')], max_length=16)),
                ('quantite', models.IntegerField(default=1, max_length=16)),
                ('sym', models.IntegerField(default=0, max_length=16)),
                ('temps_adapte', models.CharField(default=0, max_length=16)),
                ('ratio', models.FloatField(default=1, max_length=16)),
                ('livraison', models.BooleanField(default=False)),
                ('avancement_global', models.CharField(max_length=16, null=True)),
                ('id_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces')),
                ('id_sous_ensemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.sousensemble')),
            ],
        ),
    ]
