# Generated by Django 4.0.2 on 2023-04-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0026_compagnon_remove_affaires_budget_heures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancementpiece',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='avancementpiece',
            name='sym',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compagnon',
            name='temps_hebdo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification',
            field=models.IntegerField(choices=[(1, 'Peintre'), (2, 'Débiteur'), (3, 'Soudeur'), (4, 'Trappeur'), (5, 'Chaudronnier'), (6, 'Monteur')], default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='temps_estime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tache',
            name='unite',
            field=models.CharField(choices=[('K', 'kg'), ('Q', 'Qte')], default='K', max_length=15),
        ),
    ]
