# Generated by Django 4.0.2 on 2023-05-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0027_alter_avancementpiece_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancementensemble',
            name='ajustage_montage',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='debit',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='montage',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='peinture',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='soudure',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=16),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.date(2023, 5, 2), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.date(2023, 5, 2), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.date(2023, 5, 2), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.date(2023, 5, 2), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
