# Generated by Django 4.0.2 on 2023-05-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0028_alter_avancementensemble_ajustage_montage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensembles',
            name='id_avancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.avancementensemble'),
        ),
        migrations.AddField(
            model_name='pieces',
            name='id_avancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.avancementpiece'),
        ),
        migrations.AddField(
            model_name='sousensemble',
            name='id_avancement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.avancementsousensemble'),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='ajustage_montage',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='debit',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='montage',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='peinture',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementensemble',
            name='soudure',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='avancementpiece',
            name='id_piece',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='suivi.pieces'),
        ),
    ]
