# Generated by Django 4.0.2 on 2023-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0029_ensembles_id_avancement_pieces_id_avancement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='ajustage_montage',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='debit',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='decoupe_cn',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='montage',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='peinture',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AlterField(
            model_name='avancementsousensemble',
            name='soudure',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
