# Generated by Django 4.0.2 on 2023-05-03 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0030_alter_avancementsousensemble_ajustage_montage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.date(2023, 5, 3), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.date(2023, 5, 3), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.date(2023, 5, 3), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.date(2023, 5, 3), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='qualification',
            field=models.CharField(choices=[(1, 'Peintre'), (2, 'Débiteur'), (3, 'Soudeur'), (4, 'Trappeur'), (5, 'Chaudronnier'), (6, 'Monteur')], default=0, max_length=15),
        ),
    ]
