# Generated by Django 4.0.2 on 2023-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0031_alter_camions_date_depart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avancementensemble',
            old_name='debit',
            new_name='debitScie',
        ),
        migrations.RenameField(
            model_name='avancementpiece',
            old_name='debit',
            new_name='debitScie',
        ),
        migrations.RenameField(
            model_name='avancementsousensemble',
            old_name='debit',
            new_name='debitCn',
        ),
        migrations.RemoveField(
            model_name='avancementsousensemble',
            name='decoupe_cn',
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='debitCN',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='avancementensemble',
            name='usinage',
            field=models.CharField(default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='avancementpiece',
            name='debitCn',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='avancementpiece',
            name='usinage',
            field=models.CharField(choices=[('0', '0'), ('EC', 'En cours'), ('TR', 'Terminé')], default='0', max_length=4),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='debitScie',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='avancementsousensemble',
            name='usinage',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
