# Generated by Django 4.0.2 on 2023-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0032_rename_debit_avancementensemble_debitscie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancementsousensemble',
            name='avancement_global',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='qualification',
            field=models.CharField(choices=[('1', 'Peintre'), ('2', 'Débiteur'), ('3', 'Soudeur'), ('4', 'Trappeur'), ('5', 'Chaudronnier'), ('6', 'Monteur')], default='0', max_length=15),
        ),
    ]
