# Generated by Django 4.0.2 on 2023-05-04 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0033_avancementsousensemble_avancement_global_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandes',
            name='id_affaires',
        ),
        migrations.RemoveField(
            model_name='commandes',
            name='paired_commandes',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='id_affaires',
        ),
        migrations.RemoveField(
            model_name='factures',
            name='paired_factures',
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_depart',
            field=models.CharField(default=datetime.date(2023, 5, 4), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='camions',
            name='date_livraison',
            field=models.CharField(default=datetime.date(2023, 5, 4), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_commande',
            field=models.CharField(default=datetime.date(2023, 5, 4), max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='commandes',
            name='date_reception',
            field=models.CharField(default=datetime.date(2023, 5, 4), max_length=63, null=True),
        ),
        migrations.CreateModel(
            name='FactureAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
                ('id_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.factures')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.affaires')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi.commandes')),
            ],
        ),
    ]
