# Generated by Django 4.0.2 on 2023-05-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0034_remove_commandes_id_affaires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outils',
            name='image_outil',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
