# Generated by Django 4.1.7 on 2023-05-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0036_alter_camions_date_depart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avancementpiece',
            old_name='montage',
            new_name='fabrication',
        ),
        migrations.RenameField(
            model_name='avancementsousensemble',
            old_name='montage',
            new_name='fabrication',
        ),
    ]
