# Generated by Django 4.1.7 on 2023-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0037_rename_montage_avancementpiece_fabrication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avancementensemble',
            name='montage',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
