"""
Django settings for webCMC_project project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from .__init__ import *


# Build paths inside the project like this: BASE_DIR / 'subdir'.



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6fOuUt|\\^p2v0V=Bsgkx)dtf'

# SECURITY WARNING: don't run with debug turned on in production!
#if os.environ.get('ENV') == 'PRODUCTION':
DEBUG = True
#else:
#    DEBUG = True

ALLOWED_HOSTS = ['188.166.5.243']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # on utilise l'adaptateur postgresql
        'NAME': 'webcmc', # le nom de notre base de donnees creee precedemment
        'USER': 'geoffroy', # attention : remplacez par votre nom d'utilisateur
        'PASSWORD': 'CMC',
        'HOST': '',
        'PORT': '5432',
    }
}
